# Generated by Django 4.2.20 on 2025-04-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingrecord",
            name="parking_spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parking_records",
                to="parking.parkingspot",
                verbose_name="Vaga",
            ),
        ),
    ]
