# Generated by Django 4.2.20 on 2025-04-22 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customers", new_name="Customer",),
    ]
